# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CurrencyConverterWindow(object):
    def setupUi(self, CurrencyConverterWindow):
        CurrencyConverterWindow.setObjectName("CurrencyConverterWindow")
        CurrencyConverterWindow.resize(680, 350)
        CurrencyConverterWindow.setMinimumSize(QtCore.QSize(680, 350))
        CurrencyConverterWindow.setMaximumSize(QtCore.QSize(680, 350))
        self.central_widget = QtWidgets.QWidget(CurrencyConverterWindow)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.from_label = QtWidgets.QLabel(self.central_widget)
        self.from_label.setObjectName("from_label")
        self.gridLayout.addWidget(self.from_label, 2, 1, 1, 1)
        self.converted_amount = QtWidgets.QLineEdit(self.central_widget)
        self.converted_amount.setReadOnly(True)
        self.converted_amount.setObjectName("converted_amount")
        self.gridLayout.addWidget(self.converted_amount, 9, 2, 1, 1)
        self.converted_amount_label = QtWidgets.QLabel(self.central_widget)
        self.converted_amount_label.setObjectName("converted_amount_label")
        self.gridLayout.addWidget(self.converted_amount_label, 9, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 2)
        self.to_label = QtWidgets.QLabel(self.central_widget)
        self.to_label.setObjectName("to_label")
        self.gridLayout.addWidget(self.to_label, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 9, 3, 1, 1)
        self.title_label = QtWidgets.QLabel(self.central_widget)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 1, 1, 2)
        self.from_combobox = QtWidgets.QComboBox(self.central_widget)
        self.from_combobox.setObjectName("from_combobox")
        self.gridLayout.addWidget(self.from_combobox, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        self.amount = QtWidgets.QLineEdit(self.central_widget)
        self.amount.setObjectName("amount")
        self.gridLayout.addWidget(self.amount, 3, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 1, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 9, 0, 1, 1)
        self.to_combobox = QtWidgets.QComboBox(self.central_widget)
        self.to_combobox.setObjectName("to_combobox")
        self.gridLayout.addWidget(self.to_combobox, 4, 2, 1, 1)
        self.convert_button = QtWidgets.QPushButton(self.central_widget)
        self.convert_button.setObjectName("convert_button")
        self.gridLayout.addWidget(self.convert_button, 7, 1, 1, 2)
        self.amount_label = QtWidgets.QLabel(self.central_widget)
        self.amount_label.setObjectName("amount_label")
        self.gridLayout.addWidget(self.amount_label, 3, 1, 1, 1)
        CurrencyConverterWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(CurrencyConverterWindow)
        QtCore.QMetaObject.connectSlotsByName(CurrencyConverterWindow)

    def retranslateUi(self, CurrencyConverterWindow):
        _translate = QtCore.QCoreApplication.translate
        CurrencyConverterWindow.setWindowTitle(_translate("CurrencyConverterWindow", "Currency Converter"))
        self.from_label.setText(_translate("CurrencyConverterWindow", "From: "))
        self.converted_amount_label.setText(_translate("CurrencyConverterWindow", "Converted Amount: "))
        self.to_label.setText(_translate("CurrencyConverterWindow", "To: "))
        self.title_label.setText(_translate("CurrencyConverterWindow", "Convert Currency In Real Time"))
        self.convert_button.setText(_translate("CurrencyConverterWindow", "Convert"))
        self.amount_label.setText(_translate("CurrencyConverterWindow", "Amount: "))
